spring:
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
    check-template: true
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false
    # 文件上传
  servlet:
    multipart:
      enabled: true # 这个注解必须要有。表示：开启springmvc的文件上传功能
      # 单个文件大小
      max-file-size: 5MB
      # 每次请求总文件大小
      max-request-size: 10MB
shiro:
  web:
    enabled: true
  loginUrl: /login.html

