spring:
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
    check-template: true
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false
    mode: LEGACYHTML5
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 2000
    jedis:
      pool:
        # 最大连接数（负值表示无限制）
        max-active: 10
        # 最大空闲连接
        max-idle: 10
        # 最小空闲连接
        min-idle: 5

shiro:
  web:
    enabled: true
  loginUrl: /login.html
