spring:
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
    check-template: true
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false
    # 文件上传
  servlet:
    multipart:
      enabled: true # 这个注解必须要有。表示：开启springmvc的文件上传功能
      # 单个文件大小
      max-file-size: 5MB
      # 每次请求总文件大小
      max-request-size: 10MB
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 2000
    jedis:
      pool:
        # 最大连接数（负值表示无限制）
        max-active: 10
        # 最大空闲连接
        max-idle: 10
        # 最小空闲连接
        min-idle: 5
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300 # 连接的es 的服务器地址（ip+端口）
      cluster-name: elasticsearch # 连接的es服务的名称（名称不可以重复）

shiro:
  web:
    enabled: true
  loginUrl: /login.html
server:
  port: 8082
